version: "3.7"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.2
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - es-net

  app:
    build: .
    depends_on:
      - elasticsearch
    environment:
      - ES_HOST=http://elasticsearch:9200
    networks:
      - es-net
    ports:
      - "5000:5000"

volumes:
  es_data:
    driver: local

networks:
  es-net:
    driver: bridge
