version: "3.7"
services:
  elasticsearch:
    image: elasticsearch:8.8.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false   
      - http.port=9200                 
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - es-net

  app:
    build: .
    depends_on:
      - elasticsearch
    environment:
      - ES_HOST=http://elasticsearch:9200    
    networks:
      - es-net
    ports:
      - "5000:5000"

volumes:
  es_data:
    driver: local

networks:
  es-net:
    driver: bridge
